# Use new container infrastructure to enable caching
sudo: false

language: haskell 

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
  - $HOME/build/james-o-johnstone/wordcount/.stack-work

notifications:
  email: false
