# This is the simple Travis configuration, which is intended for use
# on applications which do not require cross-platform and
# multiple-GHC-version support. For more information and other
# options, see:
#
# https://docs.haskellstack.org/en/stable/travis_ci/
#
# Copy these contents into the root directory of your Github project in a file
# named .travis.yml

# Use new container infrastructure to enable caching
sudo: true 

# Do not choose a language; we provide our own build tools.
language: haskell 

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack
  - $HOME/build/james-o-johnstone/wordcount/.stack-work

# Ensure necessary system libraries are present
addons:
  apt:
    sources:
      - sourceline 'ppa:hvr/ghc' # PPA of haskell packages
    packages:
      - libgmp-dev # required by cabal
      - cabal-install-2.0 # required by GHC 8.x

ghc:
  - 8.0

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- stack --version

install:
  # Prepare Haskell environment for project
  - travis_wait 30 stack setup --no-terminal
  ## Check/show internal GHC
  - stack ghc -- --version

  - cabal install hspec

  # Build all project dependencies
  - travis_wait 40 stack build --only-dependencies --no-terminal
  
  # Build project itself
  ## Compile project with tests (`--test`) and benchmarks (`--bench`), but does not run executable (`--no-run-tests`, `--no-run-benchmarks`).
  - travis_wait 40 stack build --test --bench --no-run-tests --no-run-benchmarks --no-terminal

script:
  # Run tests
  - travis_wait 40 stack build --test --no-terminal

notifications:
  email: false
